/**
 * Options
 */
const INIT_OPTIONS = 'DEALER_ORDER_FORM_INIT_OPTIONS'

const RECEIVE_OPTIONS_STATE = 'DEALER_ORDER_FORM_RECEIVE_OPTIONS_STATE'
const RECEIVE_OPTIONS = 'DEALER_ORDER_FORM_RECEIVE_OPTIONS'
const RECEIVE_OPTIONS_PAGINATION = 'DEALER_ORDER_FORM_RECEIVE_OPTIONS_PAGINATION'
const RECEIVE_OPTIONS_SEARCH = 'DEALER_ORDER_FORM_RECEIVE_OPTIONS_SEARCH'
const RECEIVE_OPTION_STATUSES = 'DEALER_ORDER_FORM_RECEIVE_OPTION_STATUSES'
const RECEIVE_OPTION_CATEGORIES = 'DEALER_ORDER_FORM_RECEIVE_OPTION_CATEGORIES'

const SELECT_OPTION = 'DEALER_ORDER_FORM_SELECT_OPTION'
const UPDATE_OPTION = 'DEALER_ORDER_FORM_UPDATE_OPTION'

const RECEIVE_OPTIONS_ACTIVE_FLAGS = 'DEALER_ORDER_FORM_RECEIVE_OPTIONS_ACTIVE_FLAGS'

export default {
  INIT_OPTIONS,

  RECEIVE_OPTIONS_STATE,
  RECEIVE_OPTIONS,
  RECEIVE_OPTIONS_PAGINATION,
  RECEIVE_OPTIONS_SEARCH,
  RECEIVE_OPTION_STATUSES,
  RECEIVE_OPTION_CATEGORIES,

  SELECT_OPTION,
  UPDATE_OPTION,
  RECEIVE_OPTIONS_ACTIVE_FLAGS
}
