/**
 * Orders
 */
const INIT_STYLES = 'DEALER_ORDER_FORM_INIT_STYLES'

const RECEIVE_STYLES_STATE = 'DEALER_ORDER_FORM_RECEIVE_STYLES_STATE'
const RECEIVE_STYLES = 'DEALER_ORDER_FORM_RECEIVE_STYLES'
const RECEIVE_STYLES_PAGINATION = 'DEALER_ORDER_FORM_RECEIVE_STYLES_PAGINATION'
const RECEIVE_STYLES_SEARCH = 'DEALER_ORDER_FORM_RECEIVE_STYLES_SEARCH'
const RECEIVE_STYLE_STATUSES = 'DEALER_ORDER_FORM_RECEIVE_STYLE_STATUSES'

const SELECT_STYLE = 'DEALER_ORDER_FORM_SELECT_STYLE'
const UPDATE_STYLE = 'DEALER_ORDER_FORM_UPDATE_STYLE'

export default {
  INIT_STYLES,

  RECEIVE_STYLES_STATE,
  RECEIVE_STYLES,
  RECEIVE_STYLES_PAGINATION,
  RECEIVE_STYLES_SEARCH,
  RECEIVE_STYLE_STATUSES,

  SELECT_STYLE,
  UPDATE_STYLE
}
