/**
 * Orders
 */
const INIT_BUILDING_PACKAGES = 'DEALER_ORDER_FORM_INIT_BUILDING_PACKAGES'

const RECEIVE_BUILDING_PACKAGES_STATE = 'DEALER_ORDER_FORM_RECEIVE_BUILDING_PACKAGES_STATE'
const RECEIVE_BUILDING_PACKAGES = 'DEALER_ORDER_FORM_RECEIVE_BUILDING_PACKAGES'
const RECEIVE_BUILDING_PACKAGES_PAGINATION = 'DEALER_ORDER_FORM_RECEIVE_BUILDING_PACKAGES_PAGINATION'
const RECEIVE_BUILDING_PACKAGES_SEARCH = 'DEALER_ORDER_FORM_RECEIVE_BUILDING_PACKAGES_SEARCH'
const RECEIVE_BUILDING_PACKAGE_STATUSES = 'DEALER_ORDER_FORM_RECEIVE_BUILDING_PACKAGE_STATUSES'

const SELECT_BUILDING_PACKAGE = 'DEALER_ORDER_FORM_SELECT_BUILDING_PACKAGE'
const UPDATE_BUILDING_PACKAGE = 'DEALER_ORDER_FORM_UPDATE_BUILDING_PACKAGE'

const RECEIVE_BUILDING_PACKAGE_ACTIVE_FLAGS = 'DEALER_ORDER_FORM_RECEIVE_BUILDING_PACKAGE_ACTIVE_FLAGS'

export default {
  INIT_BUILDING_PACKAGES,

  RECEIVE_BUILDING_PACKAGES_STATE,
  RECEIVE_BUILDING_PACKAGES,
  RECEIVE_BUILDING_PACKAGES_PAGINATION,
  RECEIVE_BUILDING_PACKAGES_SEARCH,
  RECEIVE_BUILDING_PACKAGE_STATUSES,

  SELECT_BUILDING_PACKAGE,
  UPDATE_BUILDING_PACKAGE,
  RECEIVE_BUILDING_PACKAGE_ACTIVE_FLAGS
}
