/**
 * Modals
 */
const HIDE_COLLECT_DEPOSIT_MODAL = 'DEALER_ORDER_FORM_HIDE_COLLECT_DEPOSIT_MODAL'
const SHOW_COLLECT_DEPOSIT_MODAL = 'DEALER_ORDER_FORM_SHOW_COLLECT_DEPOSIT_MODAL'
const UPDATE_VALID_FLAG = 'DEALER_ORDER_FORM_UPDATE_COLLECT_DEPOSIT_VALID_FLAG'

export default {
    HIDE_COLLECT_DEPOSIT_MODAL,
    SHOW_COLLECT_DEPOSIT_MODAL,
    UPDATE_VALID_FLAG
}
