/**
 * Esigns
 */
const HIDE_ESIGN_EMBED = 'DEALER_ORDER_FORM_HIDE_ESIGN_EMBED_VIEW'
const SHOW_ESIGN_EMBED = 'DEALER_ORDER_FORM_SHOW_ESIGN_EMBED_VIEW'
const SET_STATE_ESIGN_EMBED = 'SDEALER_ORDER_FORM_SET_STATE_ESIGN_EMBED_VIEW'

const HIDE_ESIGN_EMAIL = 'DEALER_ORDER_FORM_HIDE_ESIGN_EMAIL_VIEW'
const SHOW_ESIGN_EMAIL = 'DEALER_ORDER_FORM_SHOW_ESIGN_EMAIL_VIEW'
const SET_STATE_ESIGN_EMAIL = 'DEALER_ORDER_FORM_SET_STATE_ESIGN_EMAIL_VIEW'

const HIDE_ALL = 'DEALER_ORDER_FORM_HIDE_ALL_ESIGN_VIEW'

export default {
  HIDE_ESIGN_EMBED,
  SHOW_ESIGN_EMBED,
  SET_STATE_ESIGN_EMBED,

  HIDE_ESIGN_EMAIL,
  SHOW_ESIGN_EMAIL,
  SET_STATE_ESIGN_EMAIL,

  HIDE_ALL
}
